#define CFG_TEXTURE_TILING 4.0

#define CFG_DIFFUSE_SCALE 1.0
#define CFG_SPECULAR_SCALE 1.0
#define CFG_GLOSS_SCALE 32.0
#define CFG_REFLECTION_SCALE 0.05

#define CFG_NORMAL_SHADOW_SCALE 0.1

#define CFG_SPECULAR_LOD 0.8
#define CFG_GLOSS_LOD 20.0

#define CFG_NORMAL_DETAIL_TILING 16.0
#define CFG_NORMAL_DETAIL_SCALE 0.3

#define CFG_FAR_TILING 0.5
#define CFG_FAR_DIFFUSE_CUTOFF 0.5
#define CFG_FAR_NORMAL_CUTOFF 0.5
#define CFG_FAR_SPECULAR_CUTOFF 0.5

#include "material.sc"
