; White

[Window]

FlatFrame = 1

AccentColorBlue = 133 64 245 ; modifies the primary color
AccentColorBrown = 161 53 55
AccentColorGreen = 33 115 70
AccentColorLime = 137 164 48
AccentColorMagenta = 216 0 115
AccentColorOrange = 208 69 37
AccentColorPink = 230 113 184
AccentColorPurple = 126 56 120
AccentColorRed = 229 20 0
AccentColorTeal = 7 114 101

BarFace = 53 53 53 ; top bar face
BarText = 170 170 170 ; top bar text
BarShadow = 238 238 238
BarHilite = 255 255 255
BarDkShadow = 34 34 34 ; color of scroll bar (bar itself) outline
BarLight = 46 46 46

[Ribbon]
RibbonFace = 0 128 0 ; green
RibbonInactiveFace = 0 128 0 ; green
RibbonSeparator = 34 34 34
RibbonLight = 0 0 128 ; navy
RibbonTabBarBackground = 53 53 53
RibbonTabBarText = 170 170 170
RibbonText = 204 204 204

RecentFileListBackground = 255 255 255
MenuPopupSeparator = 182 182 182 ; color of popupseparator
MenuPopupRect = 238 238 238
RecentFileListEdgeHighLight = 212 212 212
RecentFileListEdgeShadow = 238 238 238
GroupClientText = 59 59 59

[Toolbar]
ToolbarSeparator = 212 212 212 
ControlGalleryBk = 255 255 255

[DockingPane]
ActiveCaptionDark = 255 255 255
ActiveCaptionLight = 255 255 255
NormalCaptionDark = 255 255 255
NormalCaptionLight = 255 255 255
SplitterDark = 255 255 255
SplitterLight = 255 255 255

[TabManager]
HeaderFaceLight = 255 255 255
AccessHeader = 227 227 227
; TextColor = 59 59 59
; NormalTextColor = 59 59 59

[ReportControl]
;PressedColumnDark = 255 255 255
;PressedColumnLight = 255 255 255
;NormalColumnDark = 255 255 255
;NormalColumnLight = 255 255 255
;ColumnShadow = 255 255 255

[StatusBar]
StatusBarShadow = 46 46 46
StatusBarText = 204 204 204

[Dialog]
Background = 46 46 46
Foreground = 170 170 170