#pragma once
namespace Aya
{

namespace Text
{
enum Font
{
    FONT_LEGACY,
    FONT_ARIAL,
    FONT_ARIALBOLD,
    FONT_SOURCESANS,
    FONT_SOURCESANSBOLD,
    FONT_SOURCESANSLIGHT,
    FONT_SOURCESANSITALIC,
    FONT_BODONI,
    FONT_GARAMOND,
    FONT_CARTOON,
    FONT_CODE,
    FONT_HIGHWAY,
    FONT_SCIFI,
    FONT_ARCADE,
    FONT_FANTASY,
    FONT_ANTIQUE,
    FONT_SOURCESANSSEMIBOLD,
    FONT_GOTHAM,
    FONT_GOTHAMSEMIBOLD,
    FONT_GOTHAMBOLD,
    FONT_GOTHAMBLACK,
    FONT_AMATICSC,
    FONT_BANGERS,
    FONT_CREEPSTER,
    FONT_DENKONE,
    FONT_FONDAMENTO,
    FONT_FREDOKAONE,
    FONT_GRENZEGOTISCH,
    FONT_INDIEFLOWER,
    FONT_JOSEFINSANS,
    FONT_JURA,
    FONT_KALAM,
    FONT_LUCKIESTGUY,
    FONT_MERRIWEATHER,
    FONT_MICHROMA,
    FONT_NUNITO,
    FONT_OSWALD,
    FONT_PATRICKHAND,
    FONT_PERMANENTMARKER,
    FONT_ROBOTO,
    FONT_ROBOTOCONDENSED,
    FONT_ROBOTOMONO,
    FONT_SARPANCH,
    FONT_SPECIALELITE,
    FONT_TITILLIUMWEB,
    FONT_UBUNTU,
    FONT_NOTOSANS,
    FONT_NOTOSANSMEDIUM,
    FONT_NOTOSANSSEMIBOLD,
    FONT_NOTOSANSBOLD,
    FONT_NOTOSANSEXTRABOLD,
    FONT_NOTOSANSBLACK,
    FONT_NOTOSANSITALIC,
    FONT_NOTOSANSLIGHT,
    FONT_NOTOSANSEXTRALIGHT,
    FONT_NOTOSANSTHIN,
    FONT_CONSOLAS,
    FONT_COMICSANS,

    FONT_LAST
};
// Font drawing params - copied from G3D
enum XAlign
{
    XALIGN_RIGHT,
    XALIGN_LEFT,
    XALIGN_CENTER
};

enum YAlign
{
    YALIGN_TOP,
    /*YALIGN_BASELINE,*/ YALIGN_CENTER,
    YALIGN_BOTTOM
};


} // namespace Text
} // namespace Aya