#ifndef ROBLOX_STUDIO_VERSION_H
#define ROBLOX_STUDIO_VERSION_H

#define STRINGIFY(...) #__VA_ARGS__
#define TOSTRING(...) STRINGIFY(__VA_ARGS__)

#define VER_FILEVERSION 0, 1, 0, 0
#define VER_FILEVERSION_STR TOSTRING(VER_FILEVERSION)

#define VER_PRODUCTVERSION 0, 1, 0, 0
#define VER_PRODUCTVERSION_STR TOSTRING(VER_PRODUCTVERSION)

#define VER_COMPANYNAME_STR "Aya"
#define VER_FILEDESCRIPTION_STR "AyaStudio"
#define VER_INTERNALNAME_STR "Aya Studio"
#define VER_LEGALCOPYRIGHT_STR "Aya"
#define VER_LEGALTRADEMARKS1_STR VER_LEGALCOPYRIGHT_STR
#define VER_LEGALTRADEMARKS2_STR VER_LEGALTRADEMARKS1_STR
#define VER_ORIGINALFILENAME_STR "Aya.Studio.exe"
#define VER_PRODUCTNAME_STR "Aya Studio"

#endif // ROBLOX_STUDIO_VERSION_H
